[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar banking-web/target/banking-web-1.0-SNAPSHOT.jar --server.port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[variables]
JAVA_VERSION = "17"
MAVEN_VERSION = "3.9.6"