[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar banking-api/target/banking-api-1.0-SNAPSHOT.jar --server.port=$PORT"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[variables]
JAVA_VERSION = "17"
MAVEN_VERSION = "3.9.6"