server:
  port: ${PORT:8080}

spring:
  session:
    cookie:
      secure: true
      same-site: strict
      
  web:
    cors:
      allowed-origins:
        - "https://*.railway.app"
        - "https://your-production-web.railway.app"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

banking:
  application:
    jar-path: "./banking-application/target/banking-application-1.0-SNAPSHOT.jar"
    process-timeout: 60000
    java-command: "java"
  session:
    max-concurrent-sessions: 200
    process-idle-timeout: 300000
    cleanup-interval: 60000

logging:
  level:
    com.example.banking.api: WARN
    org.springframework.web: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"