name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: ./mvnw clean test
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: '**/target/surefire-reports/*.xml'
        reporter: java-junit
        
    - name: Build application
      run: ./mvnw clean install -DskipTests
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: banking-system-artifacts
        path: |
          banking-application/target/*.jar
          banking-api/target/*.jar
          banking-web/target/*.war
        retention-days: 7

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: banking-system-artifacts
        
    - name: Deploy to Railway (API)
      run: |
        echo "Deployment will be handled by Railway.app automatically"
        echo "This step can be enhanced with Railway CLI for advanced deployment control"
        
    - name: Deployment notification
      run: |
        echo "Banking system deployed successfully to Railway.app"
        echo "API: https://your-api-service.railway.app"
        echo "Web: https://your-web-service.railway.app"